import torch
import numpy as np
from pathlib import Path
from torch import nn, optim
from torch.utils.data import DataLoader
from datetime import datetime
import matplotlib.pyplot as plt
import torch.nn.functional as F
from collections import Counter
from itertools import product
import math
import hashlib
import io
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from matplotlib import patches
from matplotlib.patches import Patch
from torchvision import transforms
import json
from torch.utils.data import TensorDataset
import matplotlib.gridspec as gridspec

def plot_class_counter(all_targets, save_dir):

    max_target = int(max(all_targets))
    min_target = int(min(all_targets))

    counts = Counter(all_targets)
    plt.bar(
        list(counts.keys()), list(counts.values()), label=counts.keys()
    )
    plt.xlabel("Class")
    plt.ylabel("Count per class")
    plt.title("Class distribution in train set")
    for x, y in counts.items():
        plt.text(x, y, f"{y}", ha="center")

    plt.xticks([i for i in range(min_target,max_target+1)])
    plt.savefig(save_dir / "class_dist.png")
    plt.show()

def plot_item_vs_no_item(all_targets, save_dir):
    no_item = len([i for i in all_targets if i == -1])
    yes_item = len([i for i in all_targets if i != -1])

    counter = {
        "has_object":yes_item,
        "no_object": no_item
    }

    plt.bar(
        list(counter.keys()), list(counter.values()), label=counter.keys()
    )
    plt.xlabel("Class")
    plt.ylabel("Amount per class")
    plt.title("Item distribution in train set")
    for x, y in counter.items():
        plt.text(x, y, f"{y}", ha="center")

    plt.savefig(save_dir / "class_dist_items.png")
    plt.show()

def average_pixel_value(all_pixels, save_dir):
    plt.figure(figsize=(8,5))
    plt.hist(all_pixels.numpy(), bins=50, color='blue', edgecolor='black', density=True)
    plt.xlabel("Pixel value")
    plt.ylabel("Frequency")
    plt.title("Pixel value distribution in train set")
    plt.tight_layout()
    plt.savefig(save_dir / "pixel_dist.png")
    plt.show()


def pixels_outside_inside_hist(inside, outside, save_dir, label=""):
    plt.figure(figsize=(8,5))
    plt.hist(outside.numpy(), bins=50, alpha=0.6, color='blue', label='outside bbox', density=True)
    plt.hist(inside.numpy(), bins=50, alpha=0.6, color='green', label='inside bbox', density=True)
    plt.xlabel("Pixel value")
    plt.ylabel("Frequency")
    plt.title(f"Pixel value distribution for pixels inside/outside of bb (train set) {label}")
    plt.legend(handles=[
        Patch(color='blue', alpha=0.6, label='outside bbox'),
        Patch(color='green', alpha=0.6, label='inside bbox'),
        Patch(color='teal', alpha=0.6, label='overlap'),  # blue+green overlap = teal
    ])
    plt.tight_layout()
    plt.savefig(save_dir / f"inside_outside_pixel_dist_{label}.png")
    plt.show()


def score_across_datasets(final_scores, save_dir, metric = "accuracy"):
    plt.bar(
        list(final_scores.keys()), list(final_scores.values()), label=final_scores.keys()
    )
    plt.xlabel("Dataset")
    plt.ylabel(metric)
    plt.title(f"{metric} across datasets")
    for x, y in final_scores.items():
        plt.text(x, y, f"{y:.4}", ha="center")

    plt.savefig(save_dir / f"final_{metric}_scores.png")
    plt.show()


def confusion_matrix_custom(actual, pred, title, type: str, iters, save_dir):
    # fix display labels must match!
    """Code partially generated by ChatGPT"""

    cm = confusion_matrix(actual, pred)
    cm_percent = cm.astype(float) / cm.sum(axis=1)[:, np.newaxis] * 100
    cm_percent = np.nan_to_num(cm_percent)

    _fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # all
    disp1 = ConfusionMatrixDisplay(
        confusion_matrix=cm,
          display_labels=[i for i in iters]
    )
    disp1.plot(ax=axes[0], cmap=plt.cm.Blues, colorbar=False)
    axes[0].set_title(f"Counts: {title}")

    # percentages
    disp2 = ConfusionMatrixDisplay(
        confusion_matrix=cm_percent,
        display_labels=[i for i in iters]
    )
    disp2.plot(ax=axes[1], cmap=plt.cm.Blues, colorbar=True, values_format=".1f")
    axes[1].set_title(f"Percentages: {title}")

    plt.tight_layout()
    plt.savefig(save_dir / f"{title}_{type}.png")
    plt.show()
